# Generated by Django 3.0.8 on 2020-07-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='group',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
