# Generated by Django 3.0.8 on 2020-07-16 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20200716_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(max_length=500)),
                ('hosts', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('edited_timestamp', models.DateTimeField(auto_now=True)),
                ('submission_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='main.SubmissionStatus')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_events', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='events', to='main.Tag')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.EventType')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
