# Generated by Django 3.0.6 on 2020-07-15 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(related_name='resources', to='main.Tag'),
        ),
        migrations.AddField(
            model_name='grouplink',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='main.Group'),
        ),
        migrations.AddField(
            model_name='grouplink',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_links', to='main.LinkType'),
        ),
        migrations.AddField(
            model_name='group',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='main.GroupScope'),
        ),
        migrations.AddField(
            model_name='group',
            name='submission_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='main.SubmissionStatus'),
        ),
        migrations.AddField(
            model_name='group',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='groups', to='main.Tag'),
        ),
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='main.GroupType'),
        ),
        migrations.AddField(
            model_name='event',
            name='submission_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='main.SubmissionStatus'),
        ),
        migrations.AddField(
            model_name='event',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='main.Tag'),
        ),
    ]
