# Generated by Django 3.0.8 on 2020-07-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200714_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='submission_status',
        ),
        migrations.RemoveField(
            model_name='event',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='group',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='group',
            name='submission_status',
        ),
        migrations.RemoveField(
            model_name='group',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='group',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='group',
            name='type',
        ),
        migrations.RemoveField(
            model_name='grouplink',
            name='group',
        ),
        migrations.RemoveField(
            model_name='grouplink',
            name='type',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='causes',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='submission_status',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Cause',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupLink',
        ),
        migrations.DeleteModel(
            name='GroupScope',
        ),
        migrations.DeleteModel(
            name='GroupType',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
