# Generated by Django 3.0.8 on 2020-07-16 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20200716_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url', models.CharField(max_length=200)),
                ('edited_timestamp', models.DateTimeField(auto_now=True)),
                ('submission_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='main.SubmissionStatus')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_resources', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='resources', to='main.Tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='resources.Resource')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource_links', to='main.LinkType')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='resources.ResourceType'),
        ),
    ]
