# Generated by Django 3.0.8 on 2020-07-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20200716_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcelink',
            options={'ordering': ['resource__name', 'order']},
        ),
        migrations.AlterModelOptions(
            name='resourcetype',
            options={'ordering': ['display_name']},
        ),
        migrations.RenameField(
            model_name='resourcetype',
            old_name='name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='resourcetype',
            name='path_name',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
